# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPoject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
   	pod 'Alamofire'
  	pod 'IQKeyboardManagerSwift'
   	pod 'JGProgressHUD'
   	pod 'SwiftyJSON'
    	pod 'MessageKit'
   	pod 'SwiftyContextMenu'
   	pod 'Kingfisher'
	pod 'SnapKit', '~> 5.6.0'
	pod 'Then'
	pod 'Kingfisher', '~> 5.0'
	pod 'RxSwift', '6.5.0'
	pod 'RxCocoa', '6.5.0'
	pod 'RxFlow'
	pod 'lottie-ios'
	pod 'RxFlow'
	pod 'Moya', '~> 15.0'
	pod 'Moya/RxSwift'


  # Pods for GPoject

  target 'GPojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPojectUITests' do
    # Pods for testing
  end

end
